# Generated by Django 6.0 on 2026-01-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
