# Generated by Django 6.0 on 2026-01-03 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_delete_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(related_name='rsvp_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
