# Generated by Django 6.0 on 2026-01-04 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(blank=True, default='events_image/download.png', related_name='rsvp_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
